### ISSUE TITLE
where is the trial data?

### ISSUE THREAD

**Issue by mukesh-mehta** [boyuanzheng010/SemEval2021-Reading-Comprehension-of-Abstract-Meaning#1]

**Comment by Young1993** [comment]
Yes too, where is the trial data?

**Comment by Young1993** [comment]
What I understand is that the author meant that the image/ is the trial data

**Comment by boyuanzheng010** [comment]
Thank you for your interest in our task.

The trail data has been uploaded. You can find the data in this link:
https://github.com/boyuanzheng010/SemEval2021-Reading-Comprehension-of-Abstract-Meaning/tree/master/data/trail_data
Instruction about how to read data can be found in this link:
https://github.com/boyuanzheng010/SemEval2021-Reading-Comprehension-of-Abstract-Meaning

**Comment by mukesh-mehta** [comment]
Thanks for the update @boyuanzheng010.
closing the issue.
