### ISSUE TITLE
Why is the label in test data missing?

### ISSUE THREAD

**Issue by kexu-ivy** [boyuanzheng010/SemEval2021-Reading-Comprehension-of-Abstract-Meaning#6]
I am trying to use the data in my experiments but I am confused why the test data does not include the label information. 
I have tried to use the trail_data as the test data but I found the distribution of trail_data and train/dev data is pretty different, which leads to a significantly higher accuracy on the trail data than on train and dev.

**Comment by boyuanzheng010** [comment]
Thanks for your interest in this work, and consider using this dataset in your work.

This dataset is intended for the SemEval-2021. The trail_data is intended to help participants to debug their data_loading code and have an intuition about the data format. So the trail_data may not have the same distribution with train&dev. 

Here is the task competition page for reference: [SemEval-2021 Task 4: Reading Comprehension of Abstract Meaning](https://competitions.codalab.org/competitions/26153)
